#!/usr/local/bin/perl
# lakjsd flkajs dlfkj asldkjf lkasjd flkj asldkfj laksjd flkja sdlfkj laskdj flkasj dflkj asldkjf lajsd fl
# lakjsd flkajs dlfkj asldkjf lkasjd flkj asldkfj laksjd flkja sdlfkj laskdj flkasj dflkj asldkjf lajsd fl
# lakjsd flkajs dlfkj asldkjf lkasjd flkj asldkfj laksjd flkja sdlfkj laskdj flkasj dflkj asldkjf lajsd fl
# lakjsd flkajs dlfkj asldkjf lkasjd flkj asldkfj laksjd flkja sdlfkj laskdj flkasj dflkj asldkjf lajsd fl
# lakjsd flkajs dlfkj asldkjf lkasjd flkj asldkfj laksjd flkja sdlfkj laskdj flkasj dflkj asldkjf lajsd fl
# lakjsd flkajs dlfkj asldkjf lkasjd flkj asldkfj laksjd flkja sdlfkj laskdj flkasj dflkj asldkjf lajsd fl
# lakjsd flkajs dlfkj asldkjf lkasjd flkj asldkfj laksjd flkja sdlfkj laskdj flkasj dflkj asldkjf lajsd fl
# lakjsd flkajs dlfkj asldkjf lkasjd flkj asldkfj laksjd flkja sdlfkj laskdj flkasj dflkj asldkjf lajsd fl
# lakjsd flkajs dlfkj asldkjf lkasjd flkj asldkfj laksjd flkja sdlfkj laskdj flkasj dflkj asldkjf lajsd fl
# lakjsd flkajs dlfkj asldkjf lkasjd flkj asldkfj laksjd flkja sdlfkj laskdj flkasj dflkj asldkjf lajsd fl
# lakjsd flkajs dlfkj asldkjf lkasjd flkj asldkfj laksjd flkja sdlfkj laskdj flkasj dflkj asldkjf lajsd fl
# lakjsd flkajs dlfkj asldkjf lkasjd flkj asldkfj laksjd flkja sdlfkj laskdj flkasj dflkj asldkjf lajsd fl
# lakjsd flkajs dlfkj asldkjf lkasjd flkj asldkfj laksjd flkja sdlfkj laskdj flkasj dflkj asldkjf lajsd fl
# lakjsd flkajs dlfkj asldkjf lkasjd flkj asldkfj laksjd flkja sdlfkj laskdj flkasj dflkj asldkjf lajsd fl
# lakjsd flkajs dlfkj asldkjf lkasjd flkj asldkfj laksjd flkja sdlfkj laskdj flkasj dflkj asldkjf lajsd fl
# lakjsd flkajs dlfkj asldkjf lkasjd flkj asldkfj laksjd flkja sdlfkj laskdj flkasj dflkj asldkjf lajsd fl
# lakjsd flkajs dlfkj asldkjf lkasjd flkj asldkfj laksjd flkja sdlfkj laskdj flkasj dflkj asldkjf lajsd fl
# lakjsd flkajs dlfkj asldkjf lkasjd flkj asldkfj laksjd flkja sdlfkj laskdj flkasj dflkj asldkjf lajsd fl
# lakjsd flkajs dlfkj asldkjf lkasjd flkj asldkfj laksjd flkja sdlfkj laskdj flkasj dflkj asldkjf lajsd fl
# lakjsd flkajs dlfkj asldkjf lkasjd flkj asldkfj laksjd flkja sdlfkj laskdj flkasj dflkj asldkjf lajsd fl
# lakjsd flkajs dlfkj asldkjf lkasjd flkj asldkfj laksjd flkja sdlfkj laskdj flkasj dflkj asldkjf lajsd fl
# lakjsd flkajs dlfkj asldkjf lkasjd flkj asldkfj laksjd flkja sdlfkj laskdj flkasj dflkj asldkjf lajsd fl
# lakjsd flkajs dlfkj asldkjf lkasjd flkj asldkfj laksjd flkja sdlfkj laskdj flkasj dflkj asldkjf lajsd fl
# lakjsd flkajs dlfkj asldkjf lkasjd flkj asldkfj laksjd flkja sdlfkj laskdj flkasj dflkj asldkjf lajsd fl
# lakjsd flkajs dlfkj asldkjf lkasjd flkj asldkfj laksjd flkja sdlfkj laskdj flkasj dflkj asldkjf lajsd fl
# lakjsd flkajs dlfkj asldkjf lkasjd flkj asldkfj laksjd flkja sdlfkj laskdj flkasj dflkj asldkjf lajsd fl
# lakjsd flkajs dlfkj asldkjf lkasjd flkj asldkfj laksjd flkja sdlfkj laskdj flkasj dflkj asldkjf lajsd fl
# lakjsd flkajs dlfkj asldkjf lkasjd flkj asldkfj laksjd flkja sdlfkj laskdj flkasj dflkj asldkjf lajsd fl
# lakjsd flkajs dlfkj asldkjf lkasjd flkj asldkfj laksjd flkja sdlfkj laskdj flkasj dflkj asldkjf lajsd fl
# lakjsd flkajs dlfkj asldkjf lkasjd flkj asldkfj laksjd flkja sdlfkj laskdj flkasj dflkj asldkjf lajsd fl
# lakjsd flkajs dlfkj asldkjf lkasjd flkj asldkfj laksjd flkja sdlfkj laskdj flkasj dflkj asldkjf lajsd fl
# lakjsd flkajs dlfkj asldkjf lkasjd flkj asldkfj laksjd flkja sdlfkj laskdj flkasj dflkj asldkjf lajsd fl
# protect me
